apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runner-cert-pvc
  namespace: forgejo
  labels:
    app: forgejo
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:      
      storage: 50Mi
      