# Secret data.
# You will need to retrieve this from the web UI, and your Forgejo instance must be running v1.21+
# Alternatively, create this with
# kubectl create secret generic runner-secret --from-literal=token=your_offline_token_here
apiVersion: v1
kind: Secret
metadata:
  name: runner-secret
  namespace: forgejo
stringData:
  token: RUNNER_SECRET # TODO: Proper secret handling once working confirmed