apiVersion: batch/v1
kind: Job 
metadata:
  name: forgejo-setup-job
  namespace: forgejo
spec:
  backoffLimit: 15
  template:
    spec:
      containers:
      - name: forgejo
        image: IMAGE_NAME
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: forgejo-env
        - secretRef:
            name: forgejo-secrets
        volumeMounts:
        - name: forgejo-data-volume
          mountPath: /data
        command:
        - /bin/bash
        - -c
        args:
        - | 
          echo "Registering the runner"
          su -c "forgejo forgejo-cli actions register --name ${RUNNER_NAME} --secret ${RUNNER_TOKEN}" git
        env:
        - name: RUNNER_NAME
          valueFrom:
            configMapKeyRef:
              name: forgejo-runner-config
              key: runner-id
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: runner-secret
              key: token
      restartPolicy: OnFailure
      volumes:
      - name: forgejo-data-volume
        persistentVolumeClaim:
          claimName: forgejo-data-pvc
