command:
  - /bin/bash
  - -c
args:
  - |
    echo "Registering the runner"
    su -c "forgejo forgejo-cli actions register --name ${RUNNER_NAME} --secret ${RUNNER_TOKEN}" git
env:
  - name: RUNNER_NAME
    valueFrom:
      configMapKeyRef:
        name: forgejo-runner-config
        key: runner-id
  - name: RUNNER_TOKEN
    valueFrom:
      secretKeyRef:
        name: runner-secret
        key: token