apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-app-ini-config
  namespace: default
data:
  app.ini: |
    APP_NAME = Gitea meissa
    RUN_MODE = prod      # affects performance and debugging. Either “dev”, “prod” or “test”. Default: prod
    RUN_USER = git

    [repository]
    ROOT = /data/git/repositories
    DEFAULT_PRIVATE = private

    [repository.local]
    LOCAL_COPY_PATH = /data/gitea/tmp/local-repo

    [repository.upload]
    TEMP_PATH = /data/gitea/uploads

    [server]
    APP_DATA_PATH    = /data/gitea
    DOMAIN           = localhost
    SSH_DOMAIN       = localhost
    HTTP_PORT        = 3000
    ROOT_URL         = http://localhost:3000/
    DISABLE_SSH      = false
    SSH_PORT         = 22
    SSH_LISTEN_PORT  = 22
    LFS_START_SERVER = false
    LFS_CONTENT_PATH = /data/git/lfs
    ;LFS_JWT_SECRET   = 
    OFFLINE_MODE     = false

    [database]
    PATH     = /data/gitea/gitea.db
    DB_TYPE  = sqlite3
    HOST     = localhost:3306
    NAME     = gitea
    USER     = root
    PASSWD   = 
    LOG_SQL  = false
    SCHEMA   = 
    SSL_MODE = disable
    CHARSET  = utf8

    [indexer]
    ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve

    [session]
    PROVIDER_CONFIG = /data/gitea/sessions
    PROVIDER        = file

    [picture]
    AVATAR_UPLOAD_PATH            = /data/gitea/avatars
    REPOSITORY_AVATAR_UPLOAD_PATH = /data/gitea/repo-avatars
    DISABLE_GRAVATAR              = false
    ENABLE_FEDERATED_AVATAR       = true

    [attachment]
    PATH = /data/gitea/attachments

    [log]
    MODE                 = console
    LEVEL                = info
    REDIRECT_MACARON_LOG = true
    MACARON              = console
    ROUTER               = console
    ROOT_PATH            = /data/gitea/log

    [security]
    INSTALL_LOCK   = true
    ;SECRET_KEY     = 
    ;INTERNAL_TOKEN = 

    [service]
    DISABLE_REGISTRATION              = true
    REQUIRE_SIGNIN_VIEW               = false
    REGISTER_EMAIL_CONFIRM            = false
    ENABLE_NOTIFY_MAIL                = false
    EMAIL_DOMAIN_WHITELIST            = meissa-gmbh.de, meissa.de
    ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
    ENABLE_CAPTCHA                    = false
    DEFAULT_KEEP_EMAIL_PRIVATE        = true
    DEFAULT_ALLOW_CREATE_ORGANIZATION = true
    DEFAULT_ENABLE_TIMETRACKING       = true
    NO_REPLY_ADDRESS                  = noreply.localhost

    [oauth2]
    ;JWT_SECRET = 

    [mailer]
    ENABLED = false

    [openid]
    ENABLE_OPENID_SIGNIN = true
    ENABLE_OPENID_SIGNUP = true

    [federation]
    ENABLED = true
