apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-env
  namespace: default
data:
  #[attachments]
  GITEA__attachments__PATH: /data/gitea/attachments

  #[databaser]
  GITEA__database__DB_TYPE: "postgres"
  GITEA__database__HOST: "postgresql-service:5432"  # Service.Namespace.svc.cluster.local
  GITEA__database__NAME: gitea
  GITEA__database__LOG_SQL: "false"
  GITEA__database__SSL_MODE: disable
  GITEA__database__CHARSET: utf8

  #[DEFAULT]
  GITEA__DEFAULT__APP_NAME: APPNAME      # TODO: konfigurierbar machen
  GITEA__DEFAULT__RUN_MODE: prod
  GITEA__DEFAULT__RUN_USER: git

  #federation]
  GITEA__federation__ENABLED: "true"
  
  #[indexer]
  GITEA__indexer__ISSUE_INDEXER_PATH: /data/gitea/indexers/issues.bleve

  #[log]
  GITEA__log__MODE: console,file
  GITEA__log__LEVEL: Info
  GITEA__log__ROOT_PATH: /data/gitea/log

  #[mailer]
  GITEA__mailer__ENABLED: "true"
  GITEA__mailer__FROM: FROM
  GITEA__mailer__MAILER_TYPE: smtp
  GITEA__mailer__HOST: HOSTANDPORT
  GITEA__mailer__IS_TLS_ENABLED: "true"    

  #[oauth2]
  GITEA__oauth2__ENABLE: "false"

  #[picture]
  GITEA__picture__AVATAR_UPLOAD_PATH: /data/gitea/avatars
  GITEA__picture__REPOSITORY_AVATAR_UPLOAD_PATH: /data/gitea/repo-avatars
  GITEA__picture__DISABLE_GRAVATAR: "true"
  GITEA__picture__ENABLE_FEDERATED_AVATAR: "true"

  #[repository]
  GITEA__repository__ROOT: /data/git/repositories
  GITEA__repository__DEFAULT_PRIVATE: last
  GITEA__repository__LOCAL_COPY_PATH: /data/gitea/tmp/local-repo
  GITEA__repository__TEMP_PATH: /data/gitea/uploads    

  #[security]
  GITEA__security__INSTALL_LOCK: "false"

  #[server]
  GITEA__server__DOMAIN: FQDN
  GITEA__server__SSH_DOMAIN: FQDN
  GITEA__server__ROOT_URL: URL 
  GITEA__server__HTTP_PORT: "3000"
  GITEA__server__SSH_PORT: "22"

  #[service]
  GITEA__service__DISABLE_REGISTRATION: "true"  
  GITEA__service__REQUIRE_SIGNIN_VIEW: "false"
  GITEA__service__REGISTER_EMAIL_CONFIRM: "false"
  GITEA__service__ENABLE_NOTIFY_MAIL: "false"
  GITEA__service__EMAIL_DOMAIN_WHITELIST: WHITELISTDOMAINS 
  GITEA__service__ALLOW_ONLY_EXTERNAL_REGISTRATION: "false"
  GITEA__service__ENABLE_CAPTCHA: "false"
  GITEA__service__DEFAULT_KEEP_EMAIL_PRIVATE: "true"
  GITEA__service__DEFAULT_ALLOW_CREATE_ORGANIZATION: "true"
  GITEA__service__DEFAULT_ENABLE_TIMETRACKING: "true"
  GITEA__service__NO_REPLY_ADDRESS: NOREPLY  

  #[session]
  GITEA__session__PROVIDER_CONFIG: /data/gitea/sessions
  GITEA__session__PROVIDER: file
  


  
  

    

    
   
   





