apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-env
  namespace: default
data:
  GITEA__database__DB_TYPE: "postgres"
  GITEA__database__HOST: "postgresql-service:5432"  # Service.Namespace.svc.cluster.local
  GITEA__database__NAME: gitea
  GITEA__database__USER: DBUSER
  GITEA__database__PASSWD: DBPW

  GITEA__server__DOMAIN: FQDN
  GITEA__server__ROOT_URL: URL

  GITEA__mailer__ENABLED: "true"
  GITEA__mailer__FROM: gitea@meissa-gmbh.de
  GITEA__mailer__MAILER_TYPE: smtp
  GITEA__mailer__HOST: mail.routing.net:465
  GITEA__mailer__IS_TLS_ENABLED: "true"

  GITEA__service__DISABLE_REGISTRATION: "true"