apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-env
  namespace: default
data:
  #[admin]
  GITEA__admin__DEFAULT_EMAIL_NOTIFICATIONS: "enabled" # Default configuration for email notifications for users (user configurable). Options: enabled, onmention, disabled

  #[attachments]
  GITEA__attachments__PATH: /data/gitea/attachments

  #[database]
  GITEA__database__DB_TYPE: "postgres"
  GITEA__database__HOST: "postgresql-service:5432"
  GITEA__database__NAME: gitea
  GITEA__database__LOG_SQL: "false"
  GITEA__database__SSL_MODE: disable
  GITEA__database__CHARSET: utf8

  #[DEFAULT]
  APP_NAME: APPNAME
  RUN_MODE: prod
  RUN_USER: git

  #[federation]
  GITEA__federation__ENABLED: "true"
  
  #[indexer]
  GITEA__indexer__ISSUE_INDEXER_PATH: /data/gitea/indexers/issues.bleve

  #[log]
  GITEA__log__MODE: "console, file"
  GITEA__log__LEVEL: Info
  GITEA__log__ROOT_PATH: /data/gitea/log

  #[mailer]
  GITEA__mailer__ENABLED: "true"
  GITEA__mailer__FROM: FROM
  GITEA__mailer__MAILER_TYPE: smtp+startls
  GITEA__mailer__SMTP_ADDR: MAILER_HOST
  GITEA__mailer__SMTP_PORT: MAILER_PORT


  #[oauth2]
  GITEA__oauth2__ENABLE: "true"

  #[openid]
  GITEA__openid__ENABLE_OPENID: "true"
  GITEA__openid__ENABLE_OPENID_SIGNIN: "true"
  GITEA__openid__ENABLE_OPENID_SIGNUP: "true"

  #[picture]
  GITEA__picture__AVATAR_UPLOAD_PATH: /data/gitea/avatars
  GITEA__picture__REPOSITORY_AVATAR_UPLOAD_PATH: /data/gitea/repo-avatars
  GITEA__picture__DISABLE_GRAVATAR: "false"
  GITEA__picture__ENABLE_FEDERATED_AVATAR: "true" # Enable support for federated avatars (see http://www.libravatar.org).

  #[repository]
  GITEA__repository__ROOT: /data/git/repositories
  GITEA__repository__DEFAULT_PRIVATE: last
  GITEA__repository__LOCAL_COPY_PATH: /data/gitea/tmp/local-repo
  GITEA__repository__TEMP_PATH: /data/gitea/uploads    

  #[security]
  GITEA__security__INSTALL_LOCK: "false"

  #[server]
  GITEA__server__DOMAIN: FQDN
  GITEA__server__SSH_DOMAIN: FQDN
  GITEA__server__ROOT_URL: URL
  GITEA__server__HTTP_PORT: "3000"    # HTTP listen port of the server (in the pod)
  GITEA__server__SSH_PORT: "2222"     # SSH port displayed in clone URL

  #[service]
  GITEA__service__DISABLE_REGISTRATION: "false"  
  GITEA__service__REQUIRE_SIGNIN_VIEW: "false"
  GITEA__service__REGISTER_EMAIL_CONFIRM: "true"
  GITEA__service__ENABLE_NOTIFY_MAIL: "true"
  GITEA__service__EMAIL_DOMAIN_WHITELIST: WHITELISTDOMAINS 
  GITEA__service__ALLOW_ONLY_EXTERNAL_REGISTRATION: "false"
  GITEA__service__ENABLE_BASIC_AUTHENTICATION: "true"
  GITEA__service__ENABLE_CAPTCHA: "false"
  GITEA__service__DEFAULT_KEEP_EMAIL_PRIVATE: "true"
  GITEA__service__DEFAULT_ALLOW_CREATE_ORGANIZATION: "true"
  GITEA__service__DEFAULT_ENABLE_TIMETRACKING: "true"
  GITEA__service__NO_REPLY_ADDRESS: NOREPLY  

  #[session]
  GITEA__session__PROVIDER_CONFIG: /data/gitea/sessions
  GITEA__session__PROVIDER: file
