apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-app-ini-config
  namespace: default
data:
  app.ini: |
    APP_NAME = Gitea AZ2
    RUN_MODE = prod
    RUN_USER = git

    [repository]
    ROOT = /data/git/repositories

    [repository.local]
    LOCAL_COPY_PATH = /data/gitea/tmp/local-repo

    [repository.upload]
    TEMP_PATH = /data/gitea/uploads

    [server]
    APP_DATA_PATH    = /data/gitea
    DOMAIN           = localhost
    SSH_DOMAIN       = localhost
    HTTP_PORT        = 3000
    ROOT_URL         = http://localhost:3000/
    DISABLE_SSH      = false
    SSH_PORT         = 22
    SSH_LISTEN_PORT  = 22
    LFS_START_SERVER = true
    LFS_CONTENT_PATH = /data/git/lfs
    LFS_JWT_SECRET   = 6x-yxhPA88_9SagCcu1b7E5SSZmeQOX_K32IUDdjknU
    OFFLINE_MODE     = false

    [database]
    PATH     = /data/gitea/gitea.db
    DB_TYPE  = sqlite3
    HOST     = localhost:3306
    NAME     = gitea
    USER     = root
    PASSWD   = 
    LOG_SQL  = false
    SCHEMA   = 
    SSL_MODE = disable
    CHARSET  = utf8

    [indexer]
    ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve

    [session]
    PROVIDER_CONFIG = /data/gitea/sessions
    PROVIDER        = file

    [picture]
    AVATAR_UPLOAD_PATH            = /data/gitea/avatars
    REPOSITORY_AVATAR_UPLOAD_PATH = /data/gitea/repo-avatars
    DISABLE_GRAVATAR              = false
    ENABLE_FEDERATED_AVATAR       = true

    [attachment]
    PATH = /data/gitea/attachments

    [log]
    MODE                 = console
    LEVEL                = info
    REDIRECT_MACARON_LOG = true
    MACARON              = console
    ROUTER               = console
    ROOT_PATH            = /data/gitea/log

    [security]
    INSTALL_LOCK   = true
    SECRET_KEY     = UrTkoOE4Rw2BnMhqRSO7VqyCEYpmnI5YVDAnj0D0VSxEm1jiRSrUkJePj6al5j5D
    INTERNAL_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2NTM0MTEyMjB9.kUwwf2sNwOr0fJwUvXr57Krhj2OudhTmDEQCCchbnUo

    [service]
    DISABLE_REGISTRATION              = true
    REQUIRE_SIGNIN_VIEW               = false
    REGISTER_EMAIL_CONFIRM            = false
    ENABLE_NOTIFY_MAIL                = false
    ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
    ENABLE_CAPTCHA                    = false
    DEFAULT_KEEP_EMAIL_PRIVATE        = false
    DEFAULT_ALLOW_CREATE_ORGANIZATION = true
    DEFAULT_ENABLE_TIMETRACKING       = true
    NO_REPLY_ADDRESS                  = noreply.localhost

    [oauth2]
    JWT_SECRET = ZZWsXFEj1QpRO9LGGE8Z8XF46G_0LxlbQFUkacXvQjo

    [mailer]
    ENABLED = false

    [openid]
    ENABLE_OPENID_SIGNIN = true
    ENABLE_OPENID_SIGNUP = true
