kind: Service
apiVersion: v1
metadata:
  name: gitea-service
  namespace: default
spec:
  selector:
    app: gitea
  ports:
    - name: gitea-http
      port: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: gitea-ssh-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: gitea
  ports:
    - port: 22
      targetPort: 22
