apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-root-pvc
  namespace: default
  labels:
    app: gitea
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data-pvc
  namespace: default
  labels:
    app: gitea
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # TODO: Review jem - 2022/07/26 - should be configurable & as large as posible ...
      storage: 50Gi
